services:
  webtrees_db:
    image: postgres:16
    container_name: webtrees_db
    hostname: webtrees_db
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "webtrees", "-U", "webtreesusr"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /portainer/Files/AppData/Config/webtrees/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: webtrees
      POSTGRES_USER: webtreesuser
      POSTGRES_PASSWORD: webtreespass
    restart: on-failure:5

  webtrees:
    image: ghcr.io/nathanvaughn/webtrees:latest
    container_name: Webtrees
    hostname: webtrees
    security_opt:
      - no-new-privileges:true
    ports:
      - 5495:80
    volumes:
      - /portainer/Files/AppData/Config/webtrees/data:/var/www/webtrees/data:rw
    environment:
       TZ: Europe/Athens
       BASE_URL: https://webtrees.homelab # Input a correct url for your homelab
       PRETTY_URLS: TRUE
       WT_USER: schwarzspecht
       WT_PASS: webtreespwd
       WT_NAME: Your Name
       WT_EMAIL: me@email.com
       PHP_MEMORY_LIMIT: 8192M
       PHP_MAX_EXECUTION_TIME: 3600
       PHP_POST_MAX_SIZE: 512M
       PHP_UPLOAD_MAX_FILE_SIZE: 512M
       DB_HOST: webtrees_db
       DB_PORT: 5432
       POSTGRES_USER: webtreesusr
       POSTGRES_PASSWORD: webtreespwd
       DB_TYPE: pgsql
       DB_PREFIX: wt_
       POSTGRES_DB: webtrees
       HTTPS_REDIRECT: False
       HTTPS: False
    restart: on-failure:5
